# Used as tab and feed title
name: Damien's Portfolio
# Displayed in landing page
title: About Damien (aka @feugy)
# Displayed in landing page and feed
description: Software architect and craftsman
author:
  name: Damien Simonin Feugas

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-coffeescript

defaults:
  -
    scope:
      path: '' # take all files in the project
    values:
      layout: post

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: style
